---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: null
sections:
  - type: document
    label: Config
    path: _config.yml
    templates:
      - config
  - type: document
    label: Home
    path: index.md
    templates:
      - home
  - type: jekyll-pages
    label: Pages
    create: all
    templates:
      - page
  - type: jekyll-posts
    label: Posts
    create: all
    templates:
      - post
  - type: document
    label: Elements
    path: elements.md
    templates:
      - elements
upload_dir: uploads
public_path: /uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
